@host=http://localhost:3000/users

###
POST {{host}}/

###
POST {{host}}/login
Content-Type: application/json

{
  "email": "email@example.com",
  "password": "password"
}

###
POST {{host}}/register
Content-Type: application/json

{
  "email": "email@example.com",
  "password": "password"
}

###
POST {{host}}/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBleGFtcGxlLmNvbSIsIm5vbmNlIjoibnNuckFKcXlJRU1oWVdNM3Z3cDFpbFo3cTk4dEtnZGptTkFEV2JUdXkrRHl3TEtLYlFsaTkwL3BwY2V0NjhtQSIsImhhc2giOiIkMmIkMTAkVjNhQXhVVU04cjdJNUhpYUtJeXJhZTd2bjdRMU9Yem5RN01FUTN3VTlpMEtpVkhVeFNOTVMiLCJpYXQiOjE3MTE4NjYwNzMsImV4cCI6MTcxMzA3NTY3M30.5rBycQIuO_hjaM65zUHvmeDkP3uiIqCNygDhV1fotik
